### ISSUE TITLE
This package is little messy and doesn't work

### ISSUE THREAD

**Issue by memegauste** [CrashCortez/vitadock-mpv#5]
Hey, I really appreciate your work but your package is an bit mess.
Problems:
1. Unresolved dependencies:
```no ('libavutil >= 56.12.100 libavcodec >= 58.16.100 libavformat >= 58.9.100 libswscale >= 5.0.101 libavfilter >= 7.14.100 libswresample >= 3.0.100' not found)```
2. Sudo required for full automatization of script - I understand the purpose, but I rather choose tutorial over privalage escalation.
3. Code in vidware script has multiple enters - really? We live in 2019...

**Comment by CrashCortez** [comment]
Are you using the full raspbian image?

**Comment by CrashCortez** [comment]
Here is a link in the readne it explains it all. 

https://github.com/CrashCortez/vidware/blob/master/README.md
