### ISSUE TITLE
Missing sources

### ISSUE THREAD

**Issue by getwisp** [CrashCortez/vitadock-mpv#6]
The source code for udcd_uvc.skprx is missing, please make sure to upload them (possibly next to the plugin binary)

**Comment by CrashCortez** [comment]
The source code would be in the link right above software instructions setup. There is a link to the official udcd from xerpi. Also you can get it on your vita using the auto plugin program and it will set everything up. 

Unless you are asking me add it to this GitHub, which I could do if needed.
